### PR TITLE
Fix overwhelmingly annoying typo

### PR DESCRIPTION
**Pull request by tgriozel**
@jyrivallan , @tszym , please. PLEASE! :)

### CODE REVIEW

**Comment by jyrivallan** [comment]
Do you have any idea how hard it will be to deploy to production ?

**Comment by jyrivallan** [comment]
> This change is nice

I don't know, man... This wording has its charm... 🙄

**Comment by tgriozel** [comment]
hahaha noOooOoo

**Comment by tszym** [comment]
The idea is nice... as long as you don't have any idea about what it cost to build & package & put this in production.

**Comment by tszym** [comment]
This may deserve a `wontfix` label.

**Comment by axelborja** [comment]
👌

**Comment by jyrivallan** [comment]
:grammar_ci_nazi:

**Comment by tgriozel** [comment]
Seriously now, yes or no!? :D

**Comment by jyrivallan** [comment]
Depends wether _you_ want to put it into production or not (I can help)

**Comment by jyrivallan** [comment]
Sure ! But it might take a while

**Pull request merged**
