### PR TITLE
Skip test while deploying Maven snapshot artifact

### PR DESCRIPTION
**Pull request by ncolomer**
Tests are already run during the ci target

ping @damien-tinyclues

### CODE REVIEW

**Comment by ncolomer** [comment]
👍

**Comment by ncolomer** [comment]
Ping @kuhess

**Comment by kuhess** [comment]
don't you need to `-Darguments=\"-DskipTests\"` as in the release of `master`?

**Comment by ncolomer** [comment]
`<mavenVoodoo>`
`-Darguments=\"-DskipTests\"` just pass the `-DskipTests` flag to the (forked) `test` target triggered by the `release:prepare` target.
The `deploy` target is different in that it does not trigger `test` target. However, `test` target is triggered by default by maven, so we disable it (using the `-DskipTests` flag) since tests are already run by CI before Artifact.
`</mavenVoodoo>`

**Comment by kuhess** [comment]
:ok_man:

**Pull request merged**
